version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - 11543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}